image:
  - Visual Studio 2019

configuration:
  - Release

platform:
  - x64

environment:
  URL_1CV8T:
    secure: z47uplaqZaQ0ZkroXy0GP00nv6ACPwovtb+EjfPgpS0IlWM6VQd+8apwLfqT9ndX
  API_TOKEN:
    secure: 85XpT8I1bxRTZaiIA+co0b5GS05J2VOn7PzunkYlL40=

install:
  - cmd: Powershell.exe -File appveyor.deploy.ps1

build: false

cache: 1cv8.zip

artifacts:
  - path: AddIn.zip
    name: AddIn

  - path: VanessaExt.epf
    name: VanessaExt

deploy:
  - provider: GitHub
    auth_token:
      secure: v7P89NQ2I5+WGNNdhpFrZEt6OCTPf8A8VSC5rttZMXh3DJ2fTChNEjZ1Wvm3kfBt
    repository: lintest/VanessaExt
    artifact: AddIn.zip, VanessaExt.epf
    draft: true
    prerelease: true
    force_update: true
